### ISSUE TITLE
ideas for new rules

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#158]
@vogella I'm collecting some reports here so we keep the number of open issues low. See the closed issues for details and feel free to re-open when you're working on it:
- ~[x] "number or errors" #141~ (duplicate of #133; see below)
- [x] "introduction into" #140 
- [x] "to uses" #137 
- [x] "For example, " #136 
- [x] "to get rid" #134 
- [x] "number or errors" #133 
- [x] "to that" #132 
- [x] "typically is" -> "is typically" #131
- [x] "The following command show this." #181
- [x] Missing comma in ,e.g., not reported by languagetool  #130 (This is a style preference. We have a rule for this, which is by default off.)
- [x] "A soccer players kicks a ball and scores a goal." (http://languagetool-user-forum.2306527.n4.nabble.com/How-to-report-false-positive-td4643074.html)

**Comment by f-knorr** [comment]
Here are some more errors still not recognized:
[http://www.deepgrammar.com/data/snippets_with_errors.txt](http://www.deepgrammar.com/data/snippets_with_errors.txt)

**Comment by marshinkar** [comment]
All topics mentioned above have been completed.
I cannot open the file referenced in the previous comment, closing the issue now.
