### ISSUE TITLE
add profiles for different types of texts

### ISSUE THREAD

**Issue by danielnaber** [languagetool-org/languagetool#1673]
This is a follow-up to #1308.

Idea: have profiles for different kinds of text like "email", "advertising" or "scientific paper".

From the user's point of view, setting the profile must be very simple. That implies we cannot have 20 profiles that the users needs to choose from. Something like 2-5 would be okay.

From the developer's point of view, the system must be maintainable. That is, once new rules get added or rules get removed, this should work without all profiles being touched.

**Implementation**

Default should be "all rules active" (minus the ones that are not active now anyway). A language maintainer decides which rules do *not* belong to a profile. For that, rule ids and categories to be excluded from a profile can be specified in a Java class.

A more fine-grained solution is needed for the spellchecker to not accept, e.g. colloquial words. For this, the spell rule could receive a list of tags to exclude when loading data from `spelling.txt` (e.g. `#ugs` for German). 

**TODO**

- [ ] decide which profiles we need
- [ ] add a class where the profiles are defined - one class or one class per language?
- [ ] add method to that class so maintainer can specify tags to exclude from `spelling.txt`
- [ ] later, a rule with higher priority than the speller rule could provide a better message for why some words are not accepted, not just "misspelled", but "This word is colloquial and this not accepted in profile 'science paper'".

**Comment by MikeUnwalla** [comment]
> A language maintainer decides which rules do not belong to a profile.

If we assume that all grammar rules are applicable to all profiles, then aren't 'profile' and 'style' synonyms? Does it make sense to use the existing 'type' element with values such as ACADEMIC_STYLE, MARKETING_STYLE, and so on? If 'profile' and 'style' are different, what are the differences?

> A more fine-grained solution is needed for the spellchecker to not accept, e.g. colloquial words.

Yes. And also to accept technical terms that are not usually used in general texts.

**Comment by TiagoSantos81** [comment]
https://github.com/languagetool-org/languagetool/commit/7b2c2472231ebb7cb5a15f3810734cddcd109f92

This has a different way of doing it, but as long as profiles can be shipped with LT, it seems it can be used and it is a cleaner solution that just workjs on top of the `grammar.xml` work.
Would be great if it operated similarly to rule priorities, but allowing to add or exclude entire categories.
Working with rule exclusions, instead of rule inclusion make the profiles easier to maintain, while allowing the to instantly update when new rules are created.
