### ISSUE TITLE
[DE] Verfeinerung von Regeln

### ISSUE THREAD

**Issue by Dallun511** [languagetool-org/languagetool#1976]
Moin liebes LanguageTool-Team
 
***
- [ ] Ausbau der Dativregeln für femininen Kasus #1281 
Beispiel: Ich befinde mich **in deine Traumwelt.**
LT: "Keine Fehler gefunden."
***
- [ ] Ausbau der sächlichen Kasus-Regeln #1860 
Er geht **in Bett.**
Sie geht **in Auto.**
Sie geht **in Fahrzeug.**
James sagte: „Gute Frage, aber wir müssen **in Krankenhaus.**“
***
- [ ] Verfeierung mit Ajektiven zu Kasus und Nomen #1565 
**Die viele Stunden** Arbeit haben sich unserer Meinung nach bisher gelohnt.
LT: "keine Fehler gefunden."
***

Mit freundlichen Grüßen Dallun511 Ferewo
