### ISSUE TITLE
[en] false alarms PLURAL_VERB_AFTER_THIS

### ISSUE THREAD

**Issue by tiff** [languagetool-org/languagetool#2258]
> Any suggestions on how I can achieve this are most appreciated.

![Bildschirmfoto 2019-12-27 um 17 34 37](https://user-images.githubusercontent.com/37363/71524743-2d34d580-28cf-11ea-8850-f522e800c476.png)

> I’ve had this happen twice now.

![Bildschirmfoto 2019-12-27 um 17 35 41](https://user-images.githubusercontent.com/37363/71524774-5190b200-28cf-11ea-9d54-396ff719cd85.png)

> This write up is for this device.

![Bildschirmfoto 2019-12-27 um 17 37 11](https://user-images.githubusercontent.com/37363/71524834-8b61b880-28cf-11ea-869f-68579a0f483d.png)

> You can then use this tamper alert to set off the alarm using SHM.

![Bildschirmfoto 2019-12-27 um 17 40 30](https://user-images.githubusercontent.com/37363/71524956-ff9c5c00-28cf-11ea-92c0-ce6f03ee77b1.png)

> Has anyone had this happen?

![Bildschirmfoto 2019-12-27 um 17 41 52](https://user-images.githubusercontent.com/37363/71525013-31152780-28d0-11ea-945c-b4d616025797.png)

> Wouldn’t this prevent errors?
> Couldn't this prevent errors?
> Won't this prevent errors?

![Bildschirmfoto 2019-12-27 um 17 42 39](https://user-images.githubusercontent.com/37363/71525041-4e49f600-28d0-11ea-9c21-dbd9fd18b3e4.png)

> I had this happen to me for one of the older on/off versions.

![Bildschirmfoto 2019-12-27 um 17 43 57](https://user-images.githubusercontent.com/37363/71525069-7c2f3a80-28d0-11ea-893f-a2b67904c08f.png)

**Comment by MikeUnwalla** [comment]
- [ ] Any suggestions on how I can achieve this are most appreciated.
- [ ] I’ve had this happen twice now.
- [ ] This write up is for this device.
- [ ] You can then use this tamper alert to set off the alarm using SHM.
- [ ] Has anyone had this happen?
- [x] Wouldn’t this prevent errors? Fixed in #2257
- [x] Couldn't this prevent errors?  Fixed in #2257
- [x] Won't this prevent errors? Fixed in #2257
- [ ] I had this happen to me for one of the older on/off versions.

**Comment by tiff** [comment]
Wow, thanks!

**Comment by MikeUnwalla** [comment]
I didn't fix the FP with 'write up'. It should be hyphenated: https://www.lexico.com/definition/write-up

**Comment by tiff** [comment]
Yeah, we have a rule for that "WRITE_UP_HYPHEN" which isn't able to catch this yet

**Comment by tiff** [comment]
I can take care.
