### ISSUE TITLE
[en] Chunker improvement (2)

### ISSUE THREAD

**Issue by MikeUnwalla** [languagetool-org/languagetool#7090]
For rules that I worked on in LT, errors are marked as 'chunker error', usually in APs, so there is nothing to do. (Possibly [#7044](https://github.com/languagetool-org/languagetool/issues/7044)  makes an AP redundant, so you might want to check and remove redundancies.)

These are **some** errors that I noticed with my data with LanguageTool-20220911-snapshot:

Different chunks for lower case text and upper case text (the lower case text is correct):
- [ ] Sudden operation of the gyro **can** cause unwanted movement of the horizontal stabilizer. can[can/MD,B-VP]
      SUDDEN OPERATION OF THE GYRO **CAN** CAUSE UNWANTED MOVEMENT OF THE HORIZONTAL STABILIZER. CAN[can/MD,I-NP-singular]

- [ ] The lower seal comes into view when you pull the lower bearing **down**. down/B-ADVP
      THE LOWER SEAL COMES INTO VIEW WHEN YOU PULL THE LOWER BEARING **DOWN**. DOWN/no chunk

Different chunks for lower case text and initial caps text (the lower case text is correct):
- [ ] Technicians **stopped** telling supervisory managers after consultation. stopped[stop/VBD,B-VP]
      Technicians **Stopped** Telling Supervisory Managers After Consultation. Stopped[stop/VBD,I-NP-plural]

Noun for which the singular and the plural are the same. Possible solution is to use the verb that follows to decide if the noun phrase is singular or plural:
- [ ] The happy **sheep** is grazing in the field. sheep[sheep/NN,sheep/NNS,E-NP-plural], from #7044
- [ ] The shiny new **aircraft** was on the runway. aircraft[aircraft/NN,aircraft/NNS,E-NP-plural], from #7044

Other singular noun has a plural chunk:
- [ ] A **king**'s subjects must always obey the king. king[king/NN,E-NP-plural]

Adjectives incorrectly identified as verb phrases:
- [ ] Treat **retarded** growth with a small quantity of our special fertilizer. retarded[retard/VBD,B-VP]
- [ ] … or the switching of right and **left** arguments for most complex operators. left[left/JJ,left/NN:UN,leave/VBD,leave/VBN,B-VP]
- [ ] With this method, i**nspired and expired** gases are analysed to calculate the oxygen concentration. inspired[inspired/JJ,inspire/VBD,inspire/VBN,B-VP], expired[expire/VBD,expire/VBN,I-VP]
- [ ] Was that data **correct**? correct[correct/JJ,correct/VB,correct/VBP,B-VP]
- [ ] The desktop and **laminated** mouse surfaces do not have this defect. laminated[laminate/VBD,laminate/VBN,B-VP] [I added laminated/JJ to LT]
- [ ] There occasionally had been **prolonged** time periods where I forgot myself. prolonged[prolong/VBN,I-VP]
- [ ] The human heart has **left** and right ventricles. left[leave/VBN,I-VP]
- [ ] The maximum **permitted** difference is 5 eV. permitted[permit/VBD,permit/VBN,B-VP]

Nouns incorrectly identified as adverb phrases:
- [ ] He's the best **forward** that I know. forward[forward/RB,forward/JJ,forward/NN,forward/VB,forward/VBP,B-ADVP]

Nouns incorrectly identified as verb phrases:
- [ ] The other **make** sure seems good - let's buy it. make/VBP,B-VP]
- [ ] Chain **rode** is relatively heavy but resists abrasion. rode[rode/NN,ride/VBD,B-VP]
- [ ] Category:Mountain **ranges** of Switzerland, Category:Physiographic … ranges[range/NNS,range/VBZ,B-VP]
- [ ] … began on April 12, 1861, when Confederate **forces** fired upon Fort Sumter. forces[force/NNS,force/VBZ,B-VP]
- [ ] … and must **needs** be subsumed to wants? needs[needs/RB,need/NNS,need/VBZ,I-VP]
- [ ] The **does** only eat grass. does[doe/NNS,do/VBZ,B-VP]
- [ ] Include the speed **decreases** to make sure that the... decreases[decrease/NNS,decrease/VBZ,B-VP]
- [ ] The technician referred to **table** "D". table[table/NN,table/VB,table/VBP,I-VP]
- [ ] Herds of livestock are moved from place to **place** in search of pasture, fodder, and water. place[place/NN:UN,place/VB,place/VBP,I-VP]
- [ ] The small flat simply was not up to **scratch** for their needs. scratch[scratch/JJ,scratch/NN,scratch/VB,scratch/VBP,I-VP] BrE idiom: https://www.ldoceonline.com/dictionary/up-to-scratch
- [ ] This new method saves **wear and tear** on the equipment. wear[wear/NN:UN,wear/VB,wear/VBP,I-VP] and[and/CC,I-VP] tear[tear/NN,tear/VB,tear/VBP,I-VP]
- [ ] Should the paint **can** be on the table? #7088, can[can/MD,B-VP]
- [ ] …an order that will guarantee to every human **being** free access to the earth. being[being/NN:UN,be/VBG,B-VP]
- [ ] Taking the first value from each data **set**, the algorithm can be written as: set[set/NN:UN,set/VB,set/VBD,set/VBN,set/VBP,B-VP]
- [ ] Let the occasional duty **visits** be brief and bearable. visits[visit/NNS,visit/VBZ,B-VP]
- [ ] When a technician or **fitter** removes the cables, they must be careful. fitter[fitte/JJR,fitt/JJR,fit/JJR,B-VP]

Proper nouns incorrectly identified as verb phrases:
- [ ] ... if this is going to **Count Olaf**. Count[count/NN:UN,count/VB,count/VBP,I-VP]
Possible solution is to use the capitalization in the text. Thus, not: "is going to count sheep."

Verbs incorrectly identified as noun phrases:
- [ ] Did the following **work** after the modification? work[work/JJ,work/NN:UN,work/VB,work/VBP,E-NP-singular]
- [ ] Does the red container **show** signs of corrosion? show[show/NN:UN,show/VB,show/VBP,I-NP-plural]
- [ ] Do the pressures **increase**? increase[increase/NN:UN,increase/VB,increase/VBP,E-NP-singular]
- [ ] Did the pressures **increase** quickly? increase[increase/NN:UN,increase/VB,increase/VBP,E-NP-singular]
- [ ] Might the following **work** after the modification? work[work/NN:UN,E-NP-singular]
- [ ] Should all or most of the exceedingly hot water **drain** too quickly from the container, close the valve. drain[drain/NN,drain/VB,drain/VBP,E-NP-singular]
- [ ] Scott Lake, the nation's leading trainer by victories, will **stable** horses in South Florida for the first time. stable[stable/VB,B-NP-plural]
- [ ] The data will be **output** quickly. output[output/NN:UN,B-NP-singular|E-NP-singular]
- [ ] If the penetrant **sprays** on your skin, get medical aid. sprays[spray/NNS,E-NP-plural]
- [ ] If the instrument **tests** and operates correctly, tell the manager. tests[test/NNS,test/VBZ,E-NP-plural]
- [ ] Might some of the penetrant **spray** onto the cover? spray[spray/NN:UN,E-NP-singular]
- [ ] Note: should this penetrant **spray** onto your face, get medical aid. spray[spray/NN:UN,spray/VB,spray/VBP,E-NP-singular]
- [ ] Did a fly **land** on the work surface? land[land/NN,land/NN:U,E-NP-singular]
- [ ] Did the enamel on your tooth **decay** quickly? decay[decay/NN:U,decay/VB,decay/VBP,E-NP-singular]
- [ ] You must **circuit** breakers around the perimeter of the danger area. circuit[circuit/VB,B-NP-plural]
- [ ] Make sure that the arrows on the oil valve **point** away from the pipe. point[point/NN:UN,E-NP-singular]
- [ ] The pilots in the air force **fly** aircraft. fly[fly/JJ,fly/VB,fly/VBP,I-NP-plural]
- [ ] The curves of the serpent bench **form** a number of enclaves. form[form/NN:UN,E-NP-singular]
- [ ] To **sample** and plot data is not easy. sample[sample/VB,sample/VBP,B-NP-plural]
- [ ] If the message that the technician **saw** continues for more than 3 hours... saw[saw/NN,saw/VB,saw/VBP,see/VBD,E-NP-singular]
- [ ] If the message the technician **saw** continues for more than 3 hours... saw[saw/NN,saw/VB,saw/VBP,see/VBD,E-NP-singular]
- [ ] If she'd **drunk** ten cups of coffee, she would have been ill. drunk[drunk/JJ,drunk/NN,drink/VBN,B-NP-plural]
- [ ] If a defective television device **shocks** the technician, there will be a law suit. shocks[shock/VBZ,E-NP-plural]
- [ ] Let the inner shaft move **down** the pipe. move[move/NN,move/VB,move/VBP,E-NP-singular]
- [ ] Be careful when you apply the paints as to **apply** them correctly requires much skill. apply[apply/VB,B-NP-singular|E-NP-singular]
- [ ] The organization helps people who otherwise may not have **had** access to an education. had[have/VBN,B-NP-singular]
- [ ] To examine is easy, but to **sample** is difficult. sample[sample/JJ,sample/NN,sample/VB,sample/VBP,E-NP-singular]
- [ ] All I need is for Mick Jagger to ask me to **photo** one of his gigs and I'm all made up. photo[photo/VB,B-NP-singular]
- [ ] The center of gravity **moves** in relation to the load. moves[move/NNS,move/VBZ,E-NP-plural]
- [ ] Try to **station** two persons near the fuel tank. station[station/NN:UN,station/VB,station/VBP,B-NP-plural]
- [ ] His strength allows him to **muscle** shots even when he... muscle[muscle/NN:UN,muscle/VB,muscle/VBP,B-NP-plural]
- [ ] Plenty of money is available to **wine and dine** EU Ministers. wine[wine/NN:U,wine/VB,wine/VBP,B-NP-plural], dine[dine/VB,dine/VBP,I-NP-plural]
- [ ] …is a limit to their operations, but there is none to **time**. time[time/JJ,time/NN:UN,time/VB,time/VBP,B-NP-singular|E-NP-singular]
- [ ] If temperature increases **cause** problems, stop the test. cause[cause/NN:UN,cause/VB,cause/VBP,B-NP-plural]
- [ ] **Test** as many as you can. Test[Test/NNP,test/JJ,test/NN,test/VB,test/VBP,B-NP-singular|E-NP-singular]
- [ ] The United States **channels** the majority of its development fund … channels[channel/VBZ,E-NP-plural]
- [ ] Often, the technician on duty **cycles** home in the evening. cycles[cycle/NNS,cycle/VBZ,I-NP-singular]
- [ ] If the penetrant **sprays** on your skin, get medical aid. sprays[spray/NNS,E-NP-plural]
- [ ] Their new software **functions** in an interesting manner. functions[function/NNS,function/VBZ,E-NP-plural]
- [ ] Some radioactive waste **decays** slowly. decays[decay/NNS,decay/VBZ,E-NP-plural]
- [ ] The pipe **burst** during the test. burst[burst/NN,burst/VB,burst/VBD,burst/VBN,burst/VBP,E-NP-singular]
- [ ] They don't much **care**, she thinks. care[care/NN:UN,care/VB,care/VBP,E-NP-singular]
- [ ] She'd spent most of her life **flying** solo. flying[flying/JJ,flying/NN:U,fly/VBG,I-NP-singular]
- [ ] He tugged at the neck of his turtleneck sweater **feeling** like it was a noose around his neck. feeling[feeling/JJ,feeling/NN:UN,feel/VBG,E-NP-singular]
- [ ] It rubs in quickly leaving your gorgeous skin **feeling** softer after a few minutes. feeling[feeling/JJ,feeling/NN:UN,feel/VBG,E-NP-singular]
- [ ] The idea of a film project **centering** on her and her music seemed to make great sense. centering[centering/NN:UN,center/VBG,E-NP-singular]
- [ ] Quiet melodies are activated by **pressing** or squeezing a toy. pressing[press/VBG,B-NP-singular], squeezing[squeezing/NN:UN,squeeze/VBG,E-NP-singular]
- [ ] Less friction **results** in less effort involved in sliding the mouse across the surface. results[result/NNS,result/VBZ,E-NP-plural], phrasal verb: https://www.ldoceonline.com/dictionary/result-in
- [ ] They expect Jane to come home from school and **look** after the cats. look[look/NN:UN,E-NP-singular], phrasal verb: https://www.ldoceonline.com/dictionary/look-after

Verbs incorrectly identified as prepositional phrases:
- [ ] I **like** coffee and cake. like[like/VBP,B-PP]
- [ ] The technicians **like** Indonesian beer. like[like/IN,like/JJ,like/NN,like/VB,like/VBP,B-PP]
- [ ] It is necessary to **except** some sentences from the tests. except[except/IN,B-PP]

Prepositions incorrectly identified as verb phrases:
- [ ] We supply a range of integrated products and properties **including** communication tools, mobile apps and services. including[including/IN,include/VBG,B-VP]
- [ ] There are nearly 1,000 plant species **including** 14 species of cacti. including[including/IN,include/VBG,B-VP]

I have not included these types of examples:
* Ambiguous text. "Let's stop getting this biweekly." Is biweekly a noun or an adverb?
* Unlikely text. Typically, sentences that I invented for my tests.
* Texts that need much context to disambiguate. drops/verb: Pressure drops if the temperature decreases. drops/noun: Pressure drops if the temperature decreases are large.
